//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilithModConfigureTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LilithModConfigureTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Delete File 的本地化字符串。
        /// </summary>
        public static string ButtonDel {
            get {
                return ResourceManager.GetString("ButtonDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify File 的本地化字符串。
        /// </summary>
        public static string ButtonMod {
            get {
                return ResourceManager.GetString("ButtonMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New File 的本地化字符串。
        /// </summary>
        public static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Project 的本地化字符串。
        /// </summary>
        public static string MenuFileNew {
            get {
                return ResourceManager.GetString("MenuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Project 的本地化字符串。
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Project 的本地化字符串。
        /// </summary>
        public static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Languages 的本地化字符串。
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        public static string MenuLanguageChinese {
            get {
                return ResourceManager.GetString("MenuLanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string MenuLanguageEnglish {
            get {
                return ResourceManager.GetString("MenuLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clothing 的本地化字符串。
        /// </summary>
        public static string ModClothing {
            get {
                return ResourceManager.GetString("ModClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string ModItem {
            get {
                return ResourceManager.GetString("ModItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon 的本地化字符串。
        /// </summary>
        public static string ModWeapon {
            get {
                return ResourceManager.GetString("ModWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select an empty folder. 的本地化字符串。
        /// </summary>
        public static string NewNonEmptyFolder {
            get {
                return ResourceManager.GetString("NewNonEmptyFolder", resourceCulture);
            }
        }
    }
}
